-- ─────────────────────────────────────────────────────────────────────────────
-- Phase 6 Stream L (D18.1) — Skills content class: schema foundation
--
-- Per docs/decisions.md D18.1 and docs/phase-6-roadmap.md (Stream L):
-- adds the `skills` / `skill_versions` / `skill_files` / `skill_prices` tables
-- (parallel to books / book_versions / book_chapters / book_prices) and
-- extends `access_grants` to polymorphically point at either a book or a
-- skill via a nullable `skill_id` column alongside the now-nullable `book_id`.
--
-- Per-row invariant ("exactly one of book_id/skill_id is non-null") is enforced
-- via a CHECK constraint added below. The prior @@unique([subscriberId,
-- bookId, source]) is dropped because NULL-distinct unique semantics in
-- Postgres would silently allow duplicate skill grants (or duplicate book
-- grants once skill_id rows mix in); two PARTIAL unique indexes replace it,
-- one per content type.
--
-- Body sections:
--   1. SQL generated by `npx prisma migrate diff` against the schema delta
--      (CreateEnum SkillStatus, AlterTable access_grants, CreateTable for
--      the four new skill tables, indexes, foreign keys).
--   2. Hand-authored block (D18.1 §1c) — partial unique indexes + XOR CHECK.
--
-- NO BACKFILL. New tables start empty. Existing access_grants rows all have
-- book_id non-null and skill_id null — the XOR CHECK holds against current
-- production data. The pre-deploy verification `SELECT count(*) FROM
-- access_grants WHERE book_id IS NULL` must return 0 (verified before merge).
--
-- Deploy model (D18.1 §0a): commits 1–5 land on `main` as a single
-- fast-forward. Commit 1 alone is NOT individually deployable — the Stripe
-- webhook handler still upserts via `subscriberId_bookId_source` which
-- disappears with the dropped unique. Commit 4 refactors the webhook to
-- raw INSERT … ON CONFLICT. CI's `prisma migrate deploy` applies this file
-- only when all 5 commits have landed.
-- ─────────────────────────────────────────────────────────────────────────────
-- ROLLBACK SQL (operator-applied; bring app DOWN first):
--
--   ALTER TABLE "access_grants" DROP CONSTRAINT IF EXISTS "access_grants_target_xor";
--   DROP INDEX IF EXISTS "access_grants_skill_unique";
--   DROP INDEX IF EXISTS "access_grants_book_unique";
--   CREATE UNIQUE INDEX "access_grants_subscriber_id_book_id_source_key"
--     ON "access_grants" ("subscriber_id", "book_id", "source");
--   ALTER TABLE "access_grants" DROP CONSTRAINT IF EXISTS "access_grants_skill_id_fkey";
--   ALTER TABLE "access_grants" DROP COLUMN IF EXISTS "skill_id";
--   ALTER TABLE "access_grants" ALTER COLUMN "book_id" SET NOT NULL;
--   DROP TABLE IF EXISTS "skill_prices";
--   DROP TABLE IF EXISTS "skill_files";
--   DROP TABLE IF EXISTS "skill_versions";
--   DROP TABLE IF EXISTS "skills";
--   DROP TYPE  IF EXISTS "SkillStatus";
--
-- Re-application after rollback is clean — additive only, no backfill data,
-- the same `book_id IS NULL` invariant holds.
-- ─────────────────────────────────────────────────────────────────────────────

-- ═════════════════════════════════════════════════════════════════════════════
-- (1) Prisma-generated body
-- ═════════════════════════════════════════════════════════════════════════════

-- CreateEnum
CREATE TYPE "SkillStatus" AS ENUM ('ACTIVE', 'ARCHIVED');

-- DropIndex
DROP INDEX "access_grants_subscriber_id_book_id_source_key";

-- AlterTable
ALTER TABLE "access_grants" ADD COLUMN     "skill_id" UUID,
ALTER COLUMN "book_id" DROP NOT NULL;

-- CreateTable
CREATE TABLE "skills" (
    "id" UUID NOT NULL,
    "publisher_id" UUID NOT NULL,
    "publisher_user_id" UUID NOT NULL,
    "slug" VARCHAR(128) NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "description" TEXT NOT NULL,
    "status" "SkillStatus" NOT NULL DEFAULT 'ACTIVE',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "skills_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "skill_versions" (
    "id" UUID NOT NULL,
    "skill_id" UUID NOT NULL,
    "version" INTEGER NOT NULL,
    "byte_size" INTEGER NOT NULL,
    "manifest" JSONB NOT NULL,
    "normalized_hash" VARCHAR(64) NOT NULL,
    "virtual_root" VARCHAR(256),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "skill_versions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "skill_files" (
    "id" UUID NOT NULL,
    "skill_version_id" UUID NOT NULL,
    "order" INTEGER NOT NULL,
    "path" VARCHAR(512) NOT NULL,
    "extension" VARCHAR(8) NOT NULL,
    "content" TEXT NOT NULL,
    "byte_size" INTEGER NOT NULL,
    "content_hash" VARCHAR(64) NOT NULL,
    "metadata" JSONB NOT NULL DEFAULT '{}',

    CONSTRAINT "skill_files_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "skill_prices" (
    "id" UUID NOT NULL,
    "skill_id" UUID NOT NULL,
    "currency" VARCHAR(3) NOT NULL DEFAULT 'USD',
    "unit_amount_cents" INTEGER NOT NULL,
    "stripe_price_id" VARCHAR(255) NOT NULL,

    CONSTRAINT "skill_prices_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "skills_publisher_id_slug_key" ON "skills"("publisher_id", "slug");

-- CreateIndex
CREATE UNIQUE INDEX "skill_versions_skill_id_version_key" ON "skill_versions"("skill_id", "version");

-- CreateIndex
CREATE INDEX "skill_files_skill_version_id_order_idx" ON "skill_files"("skill_version_id", "order");

-- CreateIndex
CREATE UNIQUE INDEX "skill_files_skill_version_id_path_key" ON "skill_files"("skill_version_id", "path");

-- CreateIndex
CREATE UNIQUE INDEX "skill_prices_skill_id_key" ON "skill_prices"("skill_id");

-- AddForeignKey
ALTER TABLE "access_grants" ADD CONSTRAINT "access_grants_skill_id_fkey" FOREIGN KEY ("skill_id") REFERENCES "skills"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "skills" ADD CONSTRAINT "skills_publisher_id_fkey" FOREIGN KEY ("publisher_id") REFERENCES "publishers"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "skills" ADD CONSTRAINT "skills_publisher_user_id_fkey" FOREIGN KEY ("publisher_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "skill_versions" ADD CONSTRAINT "skill_versions_skill_id_fkey" FOREIGN KEY ("skill_id") REFERENCES "skills"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "skill_files" ADD CONSTRAINT "skill_files_skill_version_id_fkey" FOREIGN KEY ("skill_version_id") REFERENCES "skill_versions"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "skill_prices" ADD CONSTRAINT "skill_prices_skill_id_fkey" FOREIGN KEY ("skill_id") REFERENCES "skills"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- ═════════════════════════════════════════════════════════════════════════════
-- (2) Hand-authored block — D18.1 §1c
--
-- Partial unique indexes (one per content type) replace the dropped combined
-- unique; XOR CHECK enforces "exactly one of book_id/skill_id non-null."
-- ═════════════════════════════════════════════════════════════════════════════

-- Partial unique indexes — one per content type
CREATE UNIQUE INDEX "access_grants_book_unique"
  ON "access_grants" ("subscriber_id", "book_id", "source")
  WHERE "book_id" IS NOT NULL;

CREATE UNIQUE INDEX "access_grants_skill_unique"
  ON "access_grants" ("subscriber_id", "skill_id", "source")
  WHERE "skill_id" IS NOT NULL;

-- XOR CHECK: exactly one of (book_id, skill_id) is non-null on every row.
-- Verified pre-deploy via `SELECT count(*) FROM access_grants WHERE
-- book_id IS NULL` (must equal 0 before this migration applies — all existing
-- grants are book grants).
ALTER TABLE "access_grants"
  ADD CONSTRAINT "access_grants_target_xor"
  CHECK (("book_id" IS NULL) <> ("skill_id" IS NULL));
